name: Build, Push, and Test Docker Image (PR)

on:
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/your_image_name:latest

  test:  # Second workflow - triggered after build-and-push finishes
    runs-on: ubuntu-latest
    needs: build-and-push  # This job depends on the successful completion of build-and-push job
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker registry (optional)  # May be needed based on registry access rules
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        uses: docker/pull-action@v3
        with:
          name: ${{ secrets.DOCKER_USERNAME }}/your_image_name:latest

      - name: Run test script and check score
        run: |
          docker run your_image_name python test.py  # Replace with your actual test command
          score=$(grep -Eo '[0-9.]+' output.txt)  # Extract score from output file (modify as needed)
          if [[ $score > 0.50 ]]; then
            exit 0  # Test successful (exit code 0)
          else
            exit 1  # Test failed (exit code 1)
          fi

# This line indicates success/failure of the entire workflow based on test job exit code
outputs:
  test_passed: ${{ steps.test.outputs == 0 }}
