name: Run and Test Docker Image

on:
  pull_request:
    branches:
      - main

jobs:
  run-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image from registry
        run: docker pull sambandh/CICD_Assignment:v1

      - name: Run Docker container
        run: docker run sambandh/CICD_Assignment:v1
