name: Test

on:
  workflow_run:
    workflows: ["Train"] 
    types: 
      - completed

jobs:
  pull-and-test:
    runs-on: ubuntu-latest
    needs: build-and-push 
    steps:
      - uses: actions/checkout@v3
      - name: Pull and Test Image
        run: |
          docker login -u akashiisc -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker pull akashiisc/CICD_Assignment:latest  
          docker run akashiisc/CICD_Assignment:latest
