name: Test

on:
  workflow_run:
    workflows: Train
    branches: [main]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Log in to the Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Pull the Docker image
      run: docker pull ${{secrets.DOCKER_USERNAME }}/assgn3:latest
    - name: Run the Docker image
      run: docker run assgn3:latest
    - name: Check test score
      run: |
        score=$(docker run assgn3 | tail -1)
        if (( $(echo "$score > 0.50" |bc -l) )); then
          echo "Test passed with score $score"
        else
          echo "Test failed with score $score"
          exit 1
        fi
