name: Train

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ASSIGNMENT3
      run: docker build . --tag ASSIGNMENT3:$(date +%s)
    - name: Log in to the Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image to Docker Hub
      run: docker push ASSIGNMENT3
